### ISSUE TITLE
Q2 does not pass enough tests

### ISSUE THREAD

**Issue by mjsonofharry** [lazerzes/TeamContentsMayBeHot#7]
Pass/fail results:
```
*** PASS: test_cases/q2/0_lecture_6_tree.test
*** PASS: test_cases/q2/0_small_tree.test
*** PASS: test_cases/q2/1_1_minmax.test
*** PASS: test_cases/q2/1_2_minmax.test
*** PASS: test_cases/q2/1_3_minmax.test
*** PASS: test_cases/q2/1_4_minmax.test
*** PASS: test_cases/q2/1_5_minmax.test
*** PASS: test_cases/q2/1_6_minmax.test
*** PASS: test_cases/q2/1_7_minmax.test
*** PASS: test_cases/q2/1_8_minmax.test
*** FAIL: Exception raised: get_score() called on non-terminal state or before maximum depth achieved.
```

**Comment by mjsonofharry** [comment]
Complete traceback:
```
*** Traceback (most recent call last):
***   File "/mnt/sdc1/Repositories/TeamContentsMayBeHot/csi480/assignment2/grading.py", line 79, in grade
***     util.TimeoutFunction(getattr(grading_module, q),300)(self) # Call the question's function
***   File "/mnt/sdc1/Repositories/TeamContentsMayBeHot/csi480/assignment2/util.py", line 618, in __call__
***     result = self.function(*args, **key_args)
***   File "autograder.py", line 302, in <lambda>
***     return lambda grades: question.execute(grades)
***   File "/mnt/sdc1/Repositories/TeamContentsMayBeHot/csi480/assignment2/test_classes.py", line 65, in execute
***     if not f(grades):
***   File "autograder.py", line 297, in <lambda>
***     return lambda grades: test_case.execute(grades, module_dict, solution_dict)
***   File "multi_agent_test_classes.py", line 405, in execute
***     action, generated = self.solve_problem(multi_agents)
***   File "multi_agent_test_classes.py", line 392, in solve_problem
***     action = student_agent.get_action(self.problem.start_state)
***   File "multi_agents.py", line 189, in get_action
***     return self.minimax(game_state, 0, 0)[0]
***   File "multi_agents.py", line 160, in minimax
***     successors = [ self.minimax(successor, depth+1, agent+1)[1] for successor in successors ]
***   File "multi_agents.py", line 160, in <listcomp>
***     successors = [ self.minimax(successor, depth+1, agent+1)[1] for successor in successors ]
***   File "multi_agents.py", line 141, in minimax
***     return (None, self.evaluation_function(state))
***   File "multi_agents.py", line 111, in score_evaluation_function
***     return current_game_state.get_score()
***   File "multi_agent_test_classes.py", line 64, in get_score
***     raise Exception('get_score() called on non-terminal state or before maximum depth achieved.')
*** Exception: get_score() called on non-terminal state or before maximum depth achieved.

```

**Comment by mjsonofharry** [comment]
Parts of traceback we have control over:
```
***   File "multi_agents.py", line 189, in get_action
***     return self.minimax(game_state, 0, 0)[0]
***   File "multi_agents.py", line 160, in minimax
***     successors = [ self.minimax(successor, depth+1, agent+1)[1] for successor in successors ]
***   File "multi_agents.py", line 160, in <listcomp>
***     successors = [ self.minimax(successor, depth+1, agent+1)[1] for successor in successors ]
***   File "multi_agents.py", line 141, in minimax
***     return (None, self.evaluation_function(state))
```
Line 141 context:
```
138    def minimax(self, state, depth, agent):
139            # Check if depth reached
140            if depth == self.depth:
141                return (None, self.evaluation_function(state))
```
